---
environmentConfig:
  showOptionsConfig:
    showAddChannelButton: true
    showDefaultChannels: true
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        url: http://172.16.15.1:3000/cs-data-provider/issues
        widgets:
          - type: channel
  - name: 5thYPE
    id: "8"
    description: This is the 5thYPE organization for Larissa workshop
    sections:
      - name: Incidents
        id: "22"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/8/incidents
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "23"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/8/social_media
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/social_media/:id/chart
          - type: channels
      - name: News
        id: "26"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/8/news
        widgets:
          - name: Explore
            type: news
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/news/:id/news
          - type: channels
      - name: Policies
        id: "30"
        internal: true
        url: http://172.16.15.1:3000/cs-data-provider/organizations/8/policies
        widgets:
          - name: Components
            type: policy
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/policies/:id/template
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - name: Top 10 Most Common Policies
            type: list
            url: http://172.16.15.1:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
  - name: Deyal
    id: "7"
    description: This is the Deyal organization for Larissa workshop
    sections:
      - name: Incidents
        id: "18"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/7/incidents
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "21"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/7/social_media
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/social_media/:id/chart
          - type: channels
      - name: News
        id: "27"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/7/news
        widgets:
          - name: Explore
            type: news
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/news/:id/news
          - type: channels
      - name: Policies
        id: "31"
        internal: true
        url: http://172.16.15.1:3000/cs-data-provider/organizations/7/policies
        widgets:
          - name: Components
            type: policy
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/policies/:id/template
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - name: Top 10 Most Common Policies
            type: list
            url: http://172.16.15.1:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
  - name: Larissa
    id: "6"
    description: This is the Larissa organization for Larissa workshop
    sections:
      - name: Incidents
        id: "17"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/6/incidents
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "20"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/6/social_media
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/social_media/:id/chart
          - type: channels
      - name: News
        id: "28"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/6/news
        widgets:
          - name: Explore
            type: news
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/news/:id/news
          - type: channels
      - name: Policies
        id: "32"
        internal: true
        url: http://172.16.15.1:3000/cs-data-provider/organizations/6/policies
        widgets:
          - name: Components
            type: policy
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/policies/:id/template
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - name: Top 10 Most Common Policies
            type: list
            url: http://172.16.15.1:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
  - name: Foggia
    id: "5"
    description: This is the organization for Foggia workshop
    sections:
      - name: Incidents
        id: "25"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/5/incidents
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "16"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/5/social_media
        widgets:
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/social_media/:id/posts
          - type: channels
      - name: News
        id: "29"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/5/news
        widgets:
          - name: Explore
            type: news
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/news/:id/news
          - type: channels
      - name: Policies
        id: "33"
        internal: true
        url: http://172.16.15.1:3000/cs-data-provider/organizations/5/policies
        widgets:
          - name: Components
            type: policy
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/policies/:id/template
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/incidents/:id/graph
          - name: Top 10 Most Common Policies
            type: list
            url: http://172.16.15.1:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Exercises
        id: "24"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/5/exercises
        widgets:
          - name: Exercise
            type: exercise
            url: http://172.16.15.1:3000/cs-data-provider/organizations/5/exercises/:id/assignment
          - type: channels
  - name: Demo CS-AWARE EU
    id: "4"
    description: The organization at https://demo.cs-aware.eu/index.html
    sections:
      - name: Incidents
        id: "13"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/4/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://172.16.15.1:3000/cs-data-provider/organizations/4/incidents/:id/text_box
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/4/incidents/:id/graph
          - name: History
            type: table
            url: http://172.16.15.1:3000/cs-data-provider/organizations/4/incidents/:id/table
          - type: channel
      - name: Playbooks
        id: "19"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/4/playbooks
        widgets:
          - name: Detail
            type: cacao-playbook
            url: http://172.16.15.1:3000/cs-data-provider/organizations/4/playbooks/:id/detail
          - type: channel
  - name: Organization X
    id: "1"
    description: This is the X organization
    sections:
      - name: Incidents
        id: "3"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/1/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://172.16.15.1:3000/cs-data-provider/organizations/1/incidents/:id/text_box
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/1/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://172.16.15.1:3000/cs-data-provider/organizations/1/incidents/:id/table
          - type: channel
      - name: Stories
        id: "5"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/1/stories
        widgets:
          - name: Events
            type: timeline
            url: http://172.16.15.1:3000/cs-data-provider/organizations/1/stories/:id/timeline
          - type: channel
    widgets: []
  - name: Organization Y
    id: "2"
    description: This is the Y organization
    sections:
      - name: Incidents
        id: "6"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/2/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://172.16.15.1:3000/cs-data-provider/organizations/2/incidents/:id/text_box
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/2/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://172.16.15.1:3000/cs-data-provider/organizations/2/incidents/:id/table
          - type: channel
      - name: Stories
        id: "8"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/2/stories
        widgets:
          - name: Events
            type: timeline
            url: http://172.16.15.1:3000/cs-data-provider/organizations/2/stories/:id/timeline
          - type: channel
    widgets: []
  - name: Organization Z
    id: "3"
    description: This is the Z organization
    sections:
      - name: Incidents
        id: "9"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/3/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://172.16.15.1:3000/cs-data-provider/organizations/3/incidents/:id/text_box
          - name: System
            type: graph
            url: http://172.16.15.1:3000/cs-data-provider/organizations/3/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://172.16.15.1:3000/cs-data-provider/organizations/3/incidents/:id/table
          - type: channel
      - name: Stories
        id: "11"
        url: http://172.16.15.1:3000/cs-data-provider/organizations/3/stories
        widgets:
          - name: Events
            type: timeline
            url: http://172.16.15.1:3000/cs-data-provider/organizations/3/stories/:id/timeline
          - type: channel
    widgets: []
