---
environmentConfig:
  showOptionsConfig:
    showAddChannelButton: true
    showDefaultChannels: true
    showDirectMessages: true
  ecosystemId: "9"
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        isIssues: true
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/issues
        widgets:
          - type: channel
      - name: Participants
        id: "42"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/0/42/links
        customView: participants-link-list
      - name: Agora
        id: "43"
        internal: true
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/0/news
        widgets:
          - name: News
            type: news
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/0/news/:id/news
          - type: channel
      - name: Policies
        id: "37"
        internal: true
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/0/policies
        widgets:
          - name: Ecosystem Graph
            type: ecosystem-graph
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/issues/ecosystem_graph
          - name: Components
            type: policy
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/0/policies/:id/template
          - type: channel
      - name: Ecosystem Graph
        id: "1"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/issues/ecosystem_graph
        customView: ecosystem-graph
  - name: NextDemo CS-AWARE
    id: "10"
    description: The NextDemo organization
    sections:
      - name: Incidents
        id: "46"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/10/incidents
        widgets:
          - name: Details
            type: incident
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/10/incidents/:id/details
          - type: channel
  - name: NextDev CS-AWARE
    id: "9"
    description: The NextDev organization
    sections:
      - name: Incidents
        id: "44"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/9/incidents
        widgets:
          - name: Details
            type: incident
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/9/incidents/:id/details
          - type: channel
  - name: Demo CS-AWARE EU
    id: "4"
    description: The organization at https://demo.cs-aware.eu/index.html
    sections:
      - name: Incidents
        id: "13"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/incidents
        widgets:
          - name: Description
            type: text-box
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/incidents/:id/text_box
          - name: System
            type: graph
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/incidents/:id/graph
          - name: History
            type: table
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/incidents/:id/table
          - type: channel
      # - name: Playbooks
      #   id: "19"
      #   url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/playbooks
      #   widgets:
      #     - name: Detail
      #       type: cacao-playbook
      #       url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/playbooks/:id/detail
      #     - type: channel
      - name: Policies
        id: "34"
        internal: true
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/policies
        widgets:
          - name: Components
            type: policy
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/policies/:id/template
          - name: System
            type: graph
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/incidents/:id/graph
          - name: Top 10 Most Common Threats
            type: list
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Bundles
        id: "35"
        url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/bundles
        widgets:
          - name: Relationship
            type: bundle
            url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/bundles/:id/content
          - type: channel
      # - name: Charts
      #   id: "99"
      #   url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/charts
      #   widgets:
      #     - name: Bar Chart
      #       type: chart
      #       chartType: simple-bar
      #       url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/charts/:id/bar_chart
      #     - name: Line Chart
      #       type: chart
      #       chartType: simple-line
      #       url: https://cs-connect-demonstrator.cs-aware.eu/cs-data-provider/organizations/4/charts/:id/line_chart
      #     - type: channel
    widgets: []
