---
environmentConfig:
  showOptionsConfig:
    showAddChannelButton: true
    showDefaultChannels: true
    showDirectMessages: true
  ecosystemId: "9"
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        isIssues: true
        url: http://www.isislab.it:3000/cs-data-provider/issues
        widgets:
          - type: channel
      - name: Participants
        id: "42"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/0/42/links
        customView: participants-link-list
      - name: Agora
        id: "43"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/0/news
        widgets:
          - name: News
            type: news
            url: http://www.isislab.it:3000/cs-data-provider/organizations/0/news/:id/news
          - type: channel
      - name: Policies
        id: "37"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/0/policies
        widgets:
          - name: Ecosystem Graph
            type: ecosystem-graph
            url: http://www.isislab.it:3000/cs-data-provider/issues/ecosystem_graph
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/0/policies/:id/template
          - type: channel
      - name: Ecosystem Graph
        id: "1"
        url: http://www.isislab.it:3000/cs-data-provider/issues/ecosystem_graph
        customView: ecosystem-graph
  - name: 5thYPE
    id: "8"
    description: This is the 5thYPE organization for Larissa workshop
    sections:
      - name: Incidents
        id: "22"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "23"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/8/social_media
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/social_media/:id/chart
          - type: channels
      - name: Policies
        id: "30"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/8/policies
        widgets:
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/policies/:id/template
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents/:id/graph
          - name: Top 10 Most Common Threats
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Incidents Synthethic
        id: "40"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents_synthethic
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents_synthethic/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents_synthethic/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/8/incidents_synthethic/:id/table
          - type: channels
  - name: Deyal
    id: "7"
    description: This is the Deyal organization for Larissa workshop
    sections:
      - name: Incidents
        id: "18"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "21"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/7/social_media
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/social_media/:id/chart
          - type: channels
      - name: Policies
        id: "31"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/7/policies
        widgets:
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/policies/:id/template
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents/:id/graph
          - name: Top 10 Most Common Threats
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Incidents Synthethic
        id: "41"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents_synthethic
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents_synthethic/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents_synthethic/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/7/incidents_synthethic/:id/table
          - type: channels
  - name: Larissa
    id: "6"
    description: This is the Larissa organization for Larissa workshop
    sections:
      - name: Incidents
        id: "17"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - type: channels
      - name: Social Media
        id: "20"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/6/social_media
        widgets:
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - name: Posts
            type: social-media-posts
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/social_media/:id/posts
          - name: Posts per Hashtag
            type: chart
            chartType: simple-line
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/social_media/:id/chart
          - type: channels
      - name: Policies
        id: "32"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/6/policies
        widgets:
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/policies/:id/template
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents/:id/graph
          - name: Top 10 Most Common Threats
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Incidents Synthethic
        id: "39"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents_synthethic
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents_synthethic/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents_synthethic/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/6/incidents_synthethic/:id/table
          - type: channels
  - name: Foggia
    id: "5"
    description: This is the organization for Foggia workshop
    sections:
      - name: Policies
        id: "33"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/5/policies
        widgets:
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/policies/:id/template
          - name: Top 10 Most Common Threats
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Agora
        id: "45"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/5/news
        widgets:
          - name: News
            type: news
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/news/:id/news
          - type: channel
      - name: Expert Consultancy
        id: "36"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/5/expert_consultancies
        widgets:
          - name: What I Can Do Here
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/expert_consultancies/:id/info
          - type: channel
      - name: Education and Training
        id: "24"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/5/exercises
        widgets:
          - name: Task
            type: exercise
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/exercises/:id/assignment
          - type: channels
      - name: Incidents Synthethic
        id: "38"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/5/incidents_synthethic
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/incidents_synthethic/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/incidents_synthethic/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/5/incidents_synthethic/:id/table
          - type: channels
  - name: Demo CS-AWARE EU
    id: "4"
    description: The organization at https://demo.cs-aware.eu/index.html
    sections:
      - name: Incidents
        id: "13"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/table
          - type: channel
      - name: Playbooks
        id: "19"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/playbooks
        widgets:
          - name: Detail
            type: cacao-playbook
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/playbooks/:id/detail
          - type: channel
      - name: Policies
        id: "34"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/policies
        widgets:
          - name: Components
            type: policy
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/policies/:id/template
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/graph
          - name: Top 10 Most Common Threats
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/policies/ten_most_common
          - type: channel
      - name: Bundles
        id: "35"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/bundles
        widgets:
          - name: Relationship
            type: bundle
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/bundles/:id/content
          - type: channel
      # - name: Charts
      #   id: "99"
      #   url: http://www.isislab.it:3000/cs-data-provider/organizations/4/charts
      #   widgets:
      #     - name: Bar Chart
      #       type: chart
      #       chartType: simple-bar
      #       url: http://www.isislab.it:3000/cs-data-provider/organizations/4/charts/:id/bar_chart
      #     - name: Line Chart
      #       type: chart
      #       chartType: simple-line
      #       url: http://www.isislab.it:3000/cs-data-provider/organizations/4/charts/:id/line_chart
      #     - type: channel
  - name: NextDev CS-AWARE
    id: "9"
    description: The NextDev organization
    sections:
      - name: Incidents
        id: "44"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/9/incidents
        widgets:
          - name: Details
            type: incident
            url: http://www.isislab.it:3000/cs-data-provider/organizations/9/incidents/:id/details
          - type: channel
    widgets: []
